export const IS_AUTHENTICATION_IN_PROGRESS = "IS_AUTHENTICATION_IN_PROGRESS";
export const IS_AUTHENTICATION_ERROR = "IS_AUTHENTICATION_ERROR";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const CLEAR_ACCESS_TOKEN = "CLEAR_ACCESS_TOKEN";

export const COLLAPSE_MENU = "COLLAPSE_MENU";
export const COLLAPSE_TOGGLE = "COLLAPSE_TOGGLE";
export const NAV_CONTENT_LEAVE = "NAV_CONTENT_LEAVE";
export const NAV_COLLAPSE_LEAVE = "NAV_COLLAPSE_LEAVE";
export const FULL_SCREEN = "FULL_SCREEN";
export const FULL_SCREEN_EXIT = "FULL_SCREEN_EXIT";
export const CHANGE_LAYOUT = "CHANGE_LAYOUT";

export const SET_USER = "SET_USER";
export const GET_USER = "GET_USER";
export const IS_GETTING_USER_IN_PROGRESS = "IS_GETTING_USER_IN_PROGRESS";
export const IS_USER_ERROR = "IS_USER_ERROR";
export const IS_UPDATING_USER_IN_PROGRESS = "IS_UPDATING_USER_IN_PROGRESS";
export const IS_UPDATE_USER_ERROR = "IS_UPDATE_USER_ERROR";
export const CLEAR_USER = "CLEAR_USER";
export const IS_USER_PASSWORD_ERROR = "IS_USER_PASSWORD_ERROR";
export const IS_USER_AVATAR_ERROR = "IS_USER_AVATAR_ERROR";
export const IS_UPDATING_USER_AVATAR_IN_PROGRESS =
  "IS_UPDATING_USER_AVATAR_IN_PROGRESS";
export const IS_UPDATING_USER_PASSWORD_IN_PROGRESS =
  "IS_UPDATING_USER_PASSWORD_IN_PROGRESS";
export const SET_AVATAR_USER = "SET_AVATAR_USER";
